### PR TITLE
avoid js conflict

### PR DESCRIPTION
**Pull request by leogermani**
When sharing the checkout page with other gateways that use the same method to capture the checkout_place_order event, this plugin would conflict, because it would return true and override other gateway that might be trying to return false and avoid form submission.

This patch fixes it

### CODE REVIEW

**Comment by FERRANN23** [comment]
i have this error: 

{
	"details": [
		{
			"debug_message": "The payment_method attribute token_id is missing.",
			"message": "El parametro token_id es requerido.",
			"param": "payment_method.token_id",
			"code": "conekta.errors.parameter_validation.payment_method.token_id.missing"
		}
	],
	"object": "error",
	"type": "parameter_validation_error",
	"log_id": "58c5e283dba34d0563cafad7"
}


Can you please help me?

**Comment by Janee** [comment]
Hello,
Can you please send your woocommerce, WordPress, and your php version to soporte@conekta.com ?

Regards

Obtener Outlook para Android<https://aka.ms/ghei36>


________________________________

**Comment by leogermani** [comment]
I see that you have already fixed tokenize.js in e3443250251f7f85c9d8000c523d4c9b18f14aa4 the way I suggested here (in 01d6808).

That was the most important part of this PR. Its done, you can close it if you want.

**Comment by eduardoconekta** [comment]
thanks @leogermani we appreciate your pr's

**Pull request closed without merging**
